config/routes.rb
IphoneNote::Application.routes.draw do
  devise_for :users
  resources :notes
  root to: 'notes#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable, :recoverable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :notes, dependent: :delete_all

  attr_accessible :email, :password, :password_confirmation, :remember_me

  ID_NOT_FOUND     = 'ID_NOT_FOUND'.freeze
  PASSWORD_INVALID = 'PASSWORD_INVALID'.freeze
  def User.authenticate(email, pass)
    user = User.find_by_email(email)
    raise ActiveRecord::RecordNotFound, ID_NOT_FOUND     unless user
    raise ActiveRecord::RecordNotFound, PASSWORD_INVALID unless user.valid_password?(pass)
    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: proc { @basic_auth_token_request }
  before_filter :authenticate_user!

  protected
  def authenticate_with_basic
    return unless params['token'] and params['token'] == "token"

    request_http_basic_authentication unless authenticate_with_http_basic do |email, pass|
      begin
        if sign_in(User.authenticate(email, pass))
          logger.info "* Authenticated by basic auth: #{email}"
          @basic_auth_token_request = true
          return
        end

      rescue ActiveRecord::RecordNotFound => exception
        logger.info "[Authenticated by basic auth error] email: #{email} password: #{!!pass} (#{exception.class}: #{exception.message})"
        respond_to do |format|
          format.html { redirect_to root_path, notice: exception.message }
          format.json { render json: { errors: exception.message }.to_json, status: :unauthorized }
        end
      end
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  prepend_before_filter :authenticate_with_basic
  before_filter :load_note, only: %w(edit update destroy)

  def index
    @notes = current_user.notes.order("created_at DESC")

    respond_to do |format|
      format.html
      format.json { render json: @notes }
    end
  end

  def new
    @note = Note.new
  end

  def edit ; end

  def create
    @note = current_user.notes.build(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to notes_path, notice: 'Note was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully deleted.' }
      format.json { head :ok }
    end
  end

  private

  def load_note
    @note = current_user.notes.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="ja")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= "iPhone Note"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") iPhone Note
          .container.nav-collapse
            %ul.nav.pull-right
              - if user_signed_in?
                %li= link_to "Sign out (#{current_user.email})", destroy_user_session_path, method: :delete
              - else
                %li= link_to "Sign Up", new_user_registration_path

    .container

      .row
        .span12
          = yield

      %footer
        %p &copy; mah_lab 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/notes/_form.html.haml
= simple_form_for @note, html: {class: 'form-horizontal'} do |f|
  = f.input :title, input_html: {class: "span6"}
  = f.input :body, input_html: {rows: 5, class: "span9"}
  .form-actions
    = f.submit class: 'btn btn-primary'

app/views/notes/edit.html.haml
.well
  = render "form"

app/views/notes/index.html.haml
%p
  = link_to 'New note', new_note_path, class: 'btn'

%table.table.table-bordered
  %thead
    %tr
      %th= Note.human_attribute_name('title')
      %th= Note.human_attribute_name('body')
      %th
  %tbody
    - @notes.each do |note|
      %tr
        %td
          = note.title
        %td
          = truncate note.body, length: 100
        %td
          = link_to 'Edit', edit_note_path(note), class: 'btn'
          = link_to 'Destroy', note, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger'
    - if @notes.empty?
      %tr
        %td{colspan: 3} A note is not on the list.

app/views/notes/new.html.haml
.well
  = render "form"